export const SHOW_USER_SPINNER = 'SHOW_USER_SPINNER';
export const HIDE_USER_SPINNER = 'HIDE_USER_SPINNER';
export const SHOW_PAYMENT_SPINNER = 'SHOW_PAYMENT_SPINNER';
export const HIDE_PAYMENT_SPINNER = 'HIDE_PAYMENT_SPINNER';
export const FETCH_PAYMENT = 'FETCH_PAYMENT';
export const SET_PAYMENT = 'SET_PAYMENT';

export const SHOW_TASKS_SPINNER = 'SHOW_TASKS_SPINNER';
export const HIDE_TASKS_SPINNER = 'HIDE_TASKS_SPINNER';

export const SHOW_TASKS_DIALOG = 'SHOW_TASKS_DIALOG';
export const HIDE_TASKS_DIALOG  = 'HIDE_TASKS_DIALOG';

export const DISABLE_CREATE_BUTTON = 'DISABLE_CREATE_BUTTON';
export const ENABLE_CREATE_BUTTON = 'ENABLE_CREATE_BUTTON';

export const SHOW_TASK_INFO_DIALOG = 'SHOW_TASK_INFO_DIALOG';
export const HIDE_TASK_INFO_DIALOG  = 'HIDE_TASK_INFO_DIALOG';